# Generated by Django 4.2.16 on 2025-04-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0027_rename_fields_incomelevels_english_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='household_code',
            field=models.IntegerField(blank=True, db_column='HouseholdCode', null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='housing_code',
            field=models.CharField(blank=True, db_column='HousingCode', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='insuree',
            name='household_member',
            field=models.IntegerField(blank=True, db_column='HouseholdMember', null=True),
        ),
    ]
