# Generated by Django 4.2.11 on 2025-07-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0030_altertblProfessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesHabitation',
            fields=[
                ('idTypesHabitation', models.IntegerField(db_column='idTypesHabitation', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
            ],
            options={
                'db_table': 'tblTypesHabitation',
            },
        ),
        migrations.AddField(
            model_name='insuree',
            name='couverture_assurance_mutuelle',
            field=models.IntegerField(choices=[(1, 'Avec couverture assurance / mutuelle'), (0, 'Sans couverture')], db_column='CouvertureAssuranceMutuelle', default=0),
        ),
        migrations.AddField(
            model_name='insuree',
            name='handicap_non',
            field=models.IntegerField(choices=[(1, 'Sans handicap'), (0, 'Avec handicap')], db_column='Handicap_Non', default=1),
        ),
        migrations.AddField(
            model_name='insuree',
            name='maladie_invalidante_non',
            field=models.IntegerField(choices=[(1, 'Sans maladie invalidante'), (0, 'Avec maladie invalidante')], db_column='MaladieInvalidante_Non', default=1),
        ),
        migrations.AddField(
            model_name='insuree',
            name='milieu_de_residence',
            field=models.IntegerField(choices=[(2, 'Rural'), (1, 'Urbain')], db_column='MilieuDeResidence', default=1),
        ),
        migrations.AddField(
            model_name='insuree',
            name='types_habitation',
            field=models.ForeignKey(blank=True, db_column='TypesHabitation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.typeshabitation'),
        ),
    ]
