# Generated by Django 4.2.11 on 2025-07-03 09:12

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings



class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0031_typeshabitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouvertureAssuranceMutuelle',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('CouvertureAssuranceMutuelle', models.CharField(blank=True, db_column='CouvertureAssuranceMutuelle', max_length=150, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=150, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblCouvertureAssuranceMutuelle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Handicap_Non',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('HandicapNon', models.CharField(blank=True, db_column='HandicapNon', max_length=100, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblHandicap_Non',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maladieinvalidante_Non',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('MaladieInvalidanteNon', models.CharField(blank=True, db_column='MaladieInvalidanteNon', max_length=100, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblMaladieinvalidante_Non',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Milieuderesidence',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('Milieuderesidence', models.CharField(blank=True, db_column='MilieuDeResidence', max_length=100, null=True)),
                ('alt_language', models.CharField(blank=True, db_column='AltLanguage', max_length=100, null=True)),
                ('sort_order', models.IntegerField(blank=True, db_column='SortOrder', null=True)),
            ],
            options={
                'db_table': 'tblMilieuderésidence',
                'managed': True,
            },
        ),
        migrations.RunSQL(
            "insert into [tblCouvertureAssuranceMutuelle] ([Code], [CouvertureAssuranceMutuelle], [AltLanguage]) values (0, 'Without coverage', 'Sans couverture');"
            if settings.MSSQL else
            """insert into "tblCouvertureAssuranceMutuelle" ("Code", "CouvertureAssuranceMutuelle", "AltLanguage") values (0, 'Without coverage', 'Sans couverture');"""
        ),
        migrations.RunSQL(
            "insert into [tblCouvertureAssuranceMutuelle] ([Code], [CouvertureAssuranceMutuelle], [AltLanguage]) values (1, 'With coverage', 'Avec couverture');"
            if settings.MSSQL else
            """insert into "tblCouvertureAssuranceMutuelle" ("Code", "CouvertureAssuranceMutuelle", "AltLanguage") values (1, 'With coverage', 'Avec couverture');"""
        ),
        migrations.RunSQL(
            "insert into [tblHandicap_Non] ([Code], [HandicapNon], [AltLanguage]) values (1, 'No', 'Non');"
            if settings.MSSQL else
            """insert into "tblHandicap_Non" ("Code", "HandicapNon", "AltLanguage") values (1, 'No', 'Non');"""
        ),
        migrations.RunSQL(
            "insert into [tblHandicap_Non] ([Code], [HandicapNon], [AltLanguage]) values (0, 'Yes', 'Oui');"
            if settings.MSSQL else
            """insert into "tblHandicap_Non" ("Code", "HandicapNon", "AltLanguage") values (0, 'Yes', 'Oui');"""
        ),
        migrations.RunSQL(
            "insert into [tblMaladieinvalidante_Non] ([Code], [MaladieInvalidanteNon], [AltLanguage]) values (1, 'No', 'Non');"
            if settings.MSSQL else
            """insert into "tblMaladieinvalidante_Non" ("Code", "MaladieInvalidanteNon", "AltLanguage") values (1, 'No', 'Non');"""
        ),
        migrations.RunSQL(
            "insert into [tblMaladieinvalidante_Non] ([Code], [MaladieInvalidanteNon], [AltLanguage]) values (0, 'Yes', 'Oui');"
            if settings.MSSQL else
            """insert into "tblMaladieinvalidante_Non" ("Code", "MaladieInvalidanteNon", "AltLanguage") values (0, 'Yes', 'Oui');"""
        ),
        migrations.RunSQL(
            "insert into [tblMilieuderésidence] ([Code], [MilieuDeResidence], [AltLanguage]) values (1, 'Urban', 'Urbain');"
            if settings.MSSQL else
            """insert into "tblMilieuderésidence" ("Code", "MilieuDeResidence", "AltLanguage") values (1, 'Urban', 'Urbain');"""
        ),
        migrations.RunSQL(
            "insert into [tblMilieuderésidence] ([Code], [MilieuDeResidence], [AltLanguage]) values (2, 'Rural', 'Rural');"
            if settings.MSSQL else
            """insert into "tblMilieuderésidence" ("Code", "MilieuDeResidence", "AltLanguage") values (2, 'Rural', 'Rural');"""
        ),
        migrations.RunSQL(
            "INSERT INTO [tblTypesHabitation] VALUES "
            "(1,'Villa'),"
            "(2,'En dur et à étage'),"
            "(3,'En dur (ciment, brique cuite, ...)'),"
            "(4,'En tôle, sol en carrelage, toît en tôle'),"
            "(5,'En tôle, sol en carrelage, toit en paille'),"
            "(6,'En tôle, sol en ciment, toit en tôle'),"
            "(7,'En tôle, sol en ciment, toit en paille'),"
            "(8,'En tôle, sol en terre, toit en tôle'),"
            "(9,'En tôle, sol en terre, toit en paille'),"
            "(11,'En terre battue, sol en carrelage, toit en paille'),"
            "(12,'En terre battue, sol en ciment, toit en tôle'),"
            "(13,'En terre battue, sol en ciment, toit en paille'),"
            "(15,'En terre battue, sol en terre, toit en paille');"
            if settings.MSSQL else
            'INSERT INTO "tblTypesHabitation" VALUES '
            '(1,\'Villa\'),'
            '(2,\'En dur et à étage\'),'
            '(3,\'En dur (ciment, brique cuite, ...)\'),'
            '(4,\'En tôle, sol en carrelage, toît en tôle\'),'
            '(5,\'En tôle, sol en carrelage, toit en paille\'),'
            '(6,\'En tôle, sol en ciment, toit en tôle\'),'
            '(7,\'En tôle, sol en ciment, toit en paille\'),'
            '(8,\'En tôle, sol en terre, toit en tôle\'),'
            '(9,\'En tôle, sol en terre, toit en paille\'),'
            '(11,\'En terre battue, sol en carrelage, toit en paille\'),'
            '(12,\'En terre battue, sol en ciment, toit en tôle\'),'
            '(13,\'En terre battue, sol en ciment, toit en paille\'),'
            '(15,\'En terre battue, sol en terre, toit en paille\');'
        ),
        migrations.AlterModelOptions(
            name='typeshabitation',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='typeshabitation',
            name='idTypesHabitation',
        ),
        migrations.RemoveField(
            model_name='typeshabitation',
            name='title',
        ),
        migrations.AddField(
            model_name='typeshabitation',
            name='TypesHabitation',
            field=models.CharField(blank=True, db_column='TypesDhabitation', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='typeshabitation',
            name='alt_language',
            field=models.CharField(blank=True, db_column='AltLanguage', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='typeshabitation',
            name='code',
            field=models.IntegerField(db_column='Code', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeshabitation',
            name='sort_order',
            field=models.IntegerField(blank=True, db_column='SortOrder', null=True),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='couverture_assurance_mutuelle',
            field=models.ForeignKey(blank=True, db_column='CouvertureAssuranceMutuelle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.couvertureassurancemutuelle'),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='handicap_non',
            field=models.ForeignKey(blank=True, db_column='HandicapNon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.handicap_non'),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='maladie_invalidante_non',
            field=models.ForeignKey(blank=True, db_column='MaladieInvalidante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.maladieinvalidante_non'),
        ),
        migrations.AlterField(
            model_name='insuree',
            name='milieu_de_residence',
            field=models.ForeignKey(blank=True, db_column='MilieuDeResidence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='insuree.milieuderesidence'),
        ),
    ]
